### ISSUE TITLE
No text/pdf will load using SimpleReader or PDFReader

### ISSUE THREAD

**Issue by cleesmith** [weaviate/Verba#103]
I've tried both:
pip install goldenverba
... and:
git clone https://github.com/weaviate/Verba
pip install -e .

For both SimpleReader and PDFReader the following occurs ... not even a one line text file will load.

..................................... from Terminal output:
✔ Saved Config
ℹ Received Data to Import: READER(SimpleReader, Documents 1, Type
Documentation) CHUNKER (TokenChunker, UNITS 250, OVERLAP 50), EMBEDDER
(ADAEmbedder)
✔ Loaded 1 documents
Chunking documents: 100%|████████████████████████████████████████████████████| 1/1 [00:00<00:00, 13662.23it/s]
✔ Chunking completed
ℹ (1/1) Importing document cls.txt with 1 batches
✘ {'errors': {'error': [{'message': 'store is read-only'}]}, 'status':
'FAILED'}
Importing batches:   0%|                                                                | 0/1 [00:00<?, ?it/s]✘ {'errors': {'error': [{'message': 'store is read-only'}]}, 'status':
'FAILED'}
Importing batches: 100%|████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  2.56it/s]
✘ Loading data failed Document df91e789-78cd-4a99-970f-c9f0074a8932 not
found None
INFO:     127.0.0.1:52222 - "POST /api/load_data HTTP/1.1" 200 OK
.....................................

Did I miss something?  I followed 2 youtube videos, and the simple install on the github.
I do see usage on OpenAIs API page = 2 cents.

**Comment by stratus-ss** [comment]
I have the same problem with all 3 methods (pip, build and docker)

**Comment by FilipeBorges1993** [comment]
Same here on a M1 mac

**Comment by nicholascross** [comment]
Interestingly I found  that after this error.  I was able to query the document but it didn't appear in the list of imported documents.

**Comment by ashishakkumar** [comment]
Facing same issue on M2 pro as well

**Comment by joshuaeckroth** [comment]
It might be due to low disk space. See: https://github.com/weaviate/weaviate/issues/1931

You can fix this in your docker-compose.yml file in the weaviate section:

```
    environment:
      OPENAI_APIKEY: $OPENAI_API_KEY
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      # DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai, generative-openai, qna-openai, text2vec-cohere'
      CLUSTER_HOSTNAME: 'node1'
      DISK_USE_READONLY_PERCENTAGE: '100' <------------------
```
