### ISSUE TITLE
Unable to set ollama url

### ISSUE THREAD

**Issue by Kraego** [weaviate/Verba#240]
## Description
Vera can't connect to the ollama instance. 
```
...
✔ VERBA_Cache_mixedbread_ai_mxbai_embed_large_v1 schema created
ℹ Setting up components
✔ Config Saved in Weaviate
✘ {'errors': {'error': [{'message': 'send POST request: Post
"http://localhost:11434/api/embeddings": dial tcp [::1]:11434: connect:
connection refused'}]}, 'status': 'FAILED'}
....
```

OLLAMA_URL is configured. Output from running vera container:

```
root@88dbf882ab81:/Verba# env | grep OLLAMA
OLLAMA_EMBED_MODEL=mxbai-embed-large
OLLAMA_MODEL=llama3
OLLAMA_URL=http://ollama:11434
```

I've also checked the code, the OllamaEmbedder should load the value from the environment variable (`self.url = os.environ.get("OLLAMA_URL", "")
`

**How is this log message even possible?** What I'm doing wrong? If you need more information ask anytime. 

## Is this a bug or a feature?
- [x] Bug
- [ ] Feature

## Steps to Reproduce
Run `docker compose up -d`, compose file and env. see below: 
`commit 5f312a263b82cbc566ae8dabf71bce04f78459b1 (HEAD -> main, origin/main, origin/HEAD)`

## Additional context
docker-compose.yml:

```yaml
---
services:
  verba:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      VERBA_PRODUCTION: ${VERBA_PRODUCTION}
      WEAVIATE_URL_VERBA: ${WEAVIATE_URL_VERBA}
      OLLAMA_URL: ${OLLAMA_URL}
      OLLAMA_MODEL: ${OLLAMA_MODEL}
      OLLAMA_EMBED_MODEL: ${OLLAMA_EMBED_MODEL}
      ## IF YOU WANT AUTHENTICATION, UNCOMENT BELLOW 
      ## AND ADD WEAVIATE SERVICE
      #- WEAVIATE_API_KEY_VERBA: ${WEAVIATE_API_KEY_VERBA}
    volumes:
      - ./data:/data/
    depends_on:
      weaviate:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s

  weaviate:
    command:
    - --host
    - 0.0.0.0
    - --port
    - '8080'
    - --scheme
    - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.25.4
    ports:
    - 8080:8080
    - 50051:50051
    volumes:
    - ./weaviate_data:/var/lib/weaviate
    restart: on-failure:0
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8080/v1/.well-known/ready || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      #- WEAVIATE_API_KEY_VERBA=$WEAVIATE_API_KEY_VERBA
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-ollama'
      ENABLE_MODULES: 'text2vec-ollama,generative-ollama,text2vec-huggingface'
      CLUSTER_HOSTNAME: 'node1'

  ollama:
    image: ollama/ollama
    ports:
    - 11434:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    tty: true
    restart: always
    environment:
      OLLAMA_KEEP_ALIVE: '24h'
      OLLAMA_HOST: '0.0.0.0'

volumes:
  weaviate_data: {}
...
```
env File:
```
HUGGINGFACE_APIKEY=S3cr3t

VERBA_PRODUCTION=true
# URL-TO-YOUR-WEAVIATE-CLUSTER
WEAVIATE_URL_VERBA=http://weaviate:8080

# API-KEY-OF-YOUR-WEAVIATE-CLUSTER
#WEAVIATE_API_KEY_VERBA=superS3cr3t

OLLAMA_URL=http://ollama:11434
OLLAMA_MODEL=llama3
OLLAMA_EMBED_MODEL=mxbai-embed-large
```
