### ISSUE TITLE
Is there a Docker Compose that works and avoids using Ollama?

### ISSUE THREAD

**Issue by danielrosehill** [weaviate/Verba#364]
Hi!

I'm trying to deploy Verba on a VPS. 

I was under the impression that it is possible to use an external LLM with the app. 

As the VPS I'm running on isn't really provisioned for running an LLM, I would rather just use cloud LLMs via APIs. 

I attempted to modify the default docker-compose in this repo a little bit until I ended up with something like this:

```
services:
  verba:
    image: semitechnologies/verba:latest
    expose:
      - 8000
    environment:
      - WEAVIATE_URL_VERBA=http://weaviate:8080
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - COHERE_API_KEY=${COHERE_API_KEY}
      - UNSTRUCTURED_API_KEY=${UNSTRUCTURED_API_KEY:-}
      - UNSTRUCTURED_API_URL=${UNSTRUCTURED_API_URL:-}
      - GITHUB_TOKEN=${GITHUB_TOKEN:-}
      - EMBEDDING_MODEL=openai # Specify to use OpenAI instead of Ollama
      - LLM_MODEL=openai # Specify to use OpenAI instead of Ollama
    volumes:
      - /root/app-data/verba/data:/data/
    depends_on:
      weaviate:
        condition: service_healthy
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8000 || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - cloudflared

  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: semitechnologies/weaviate:1.25.10
    expose:
      - 8080
    volumes:
      - /root/app-data/verba/weaviate:/var/lib/weaviate
    restart: on-failure:0
    healthcheck:
      test: wget --no-verbose --tries=3 --spider http://localhost:8080/v1/.well-known/ready || exit 1
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    environment:
      OPENAI_APIKEY: ${OPENAI_API_KEY}
      COHERE_APIKEY: ${COHERE_API_KEY}
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      ENABLE_MODULES: 'e'
      CLUSTER_HOSTNAME: 'node1'
    networks:
      - cloudflared

networks:
  cloudflared:
    external: true
```

But looking at the container logs, it seems as if the main container is expecting the OLAMA API to be available. 

Is there any way to avoid OLAMA entirely and if so, is there any chance you have a Docker Compose template for that?
